'use client'

import type {Metadata} from 'next'
import {Ubuntu} from 'next/font/google'
import React from "react";
import styles from "./common/styles/common.module.scss"
import {DictionaryProvider} from "@/app/context/DictionaryContext";
import {Locale} from "@/app/types/dictionary.model";
import cls from "classnames";
import "normalize.css/normalize.css";

const inter = Ubuntu({weight: '300', subsets: ["latin"]})

const metadata: Metadata = {
    title: 'Finance helper - application which help you ',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                       params
                                   }: {
    children: React.ReactNode,
    params: { lang: Locale }
}) {

    return (
        <html lang={params.lang}>
        <body className={cls(inter.className, styles.app)}>
        <div className={styles.app}>
            <DictionaryProvider lang={params.lang}>
                {children}
            </DictionaryProvider>
        </div>
        </body>
        </html>
    )
}
