import type {Metadata} from 'next'
import {Ubuntu} from 'next/font/google'
import React from "react";
import styles from "./common/styles/common.module.scss"
import cls from "classnames";
import Header from "@/app/components/header/header.component";

const inter = Ubuntu({weight: '300', subsets: ["latin"]})

const metadata: Metadata = {
    title: 'Finance helper - application which help you ',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html>
        <body className={cls(inter.className, styles.app)}>
        <div className={styles.app}>
            <Header/>
            {/*<Body>{children}</Body>*/}
        </div>
        </body>
        </html>
    )
}
