'use client'

import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import React, {useMemo} from "react";
import {usePathname, useRouter} from "next/navigation";
import {Button} from "@mui/material";

const inter = Inter({subsets: ['latin']})

const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    const router = useRouter();
    const pathname = usePathname();
    const isMainPage = useMemo(() => {
        return pathname.includes("/welcome");
    }, [pathname])

    return (
        <html lang="en">
        <body className={inter.className}>
        {
            !isMainPage && <Button onClick={() => router.back()}>Back</Button>
        }
        {children}
        </body>
        </html>
    )
}
